baseURL = 'https://hugoforge.com/'
title = 'hugo://forge'
theme = 'forge'
defaultContentLanguage = 'no'
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[languages]
  [languages.no]
    label = 'Norsk'
    locale = 'nb'
    weight = 1
    contentDir = 'content/no'
    [languages.no.params]
      description = "Rask migrering av nettsider fra WordPress og Drupal til Hugo"

  [languages.en]
    label = 'English'
    locale = 'en'
    weight = 2
    contentDir = 'content/en'
    [languages.en.params]
      description = "Fast static site migrations from WordPress & Drupal to Hugo"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
